include("support/setup.jl")

include("binding/basic.jl")
include("binding/regressions.jl")
include("concurrency/threading.jl")
include("mixed/catalysis.jl")
include("NativePolyhedra/runtests.jl")
include("legacy/smoke.jl")
include("output/symbolics.jl")
include("siso/workflows.jl")
include("backends/cdd_bridge.jl")
