"""
Forward declarations for public API bindings.

Julia 1.12 tightened world-age semantics for global bindings, especially under
Revise. Declaring the bindings up front keeps them stable while methods are
added or updated during development.
"""

function update_catalysis! end
function locate_sym_x end
function locate_sym_qK end
function pythonprint end
function N_generator end
function L_generator end
function randomize end
function x2qK end
function qK2x end
function x_traj_with_qK_change end
function x_traj_with_q_change end
function x_traj_cat end
function qK_traj_cat end
function q_traj_cat end
function calc_volume end
function logder_x_qK end
function logder_qK_x end
function ∂logx_∂logqK end
function ∂logqK_∂logx end
function find_all_vertices end
function find_all_vertices! end
function get_vertices_perm_dict end
function get_nullities end
function get_volumes end
function have_perm end
function get_vertices end
function is_singular end
function is_asymptotic end
function n_vertices end
function get_idx end
function get_perm end
function get_vertex end
function get_neighbors end
function get_nullity end
function get_one_inner_point end
function get_P_P0 end
function get_P end
function get_P0 end
function get_M_M0 end
function get_M end
function get_M0 end
function get_H_H0 end
function get_H end
function get_H0 end
function get_C_C0_x end
function get_C_x end
function get_C0_x end
function get_C_C0_nullity_qK end
function get_C_C0_qK end
function get_C_qK end
function get_C0_qK end
function get_C_C0_nullity end
function get_C_C0 end
function get_C end
function get_C0 end
function check_feasibility_with_constraint end
function feasible_vertieces_with_constraint end
function get_polyhedron end
function get_volume end
function is_neighbor end
function get_interface end
function get_change_dir end
function get_function end
function assign_vertex end
function assign_vertex_qK end
function assign_vertex_x end
function x_sym end
function q_sym end
function K_sym end
function qK_sym end
function ∂logqK_∂logx_sym end
function ∂logx_∂logqK_sym end
function logder_qK_x_sym end
function logder_x_qK_sym end
function show_condition_poly end
function show_condition_x end
function show_condition_qK end
function show_condition end
function show_expression_mapping end
function show_expression_x end
function show_expression_qK end
function show_expression_path end
function show_dominant_condition end
function show_conservation end
function show_equilibrium end
function show_interface end
function sym_direction end
function print_path end
function print_paths end
function format_arrow end
function get_vertices_graph! end
function get_polyhedra end
function get_SISO_graph end
function get_path end
function get_edge end
function get_intersect end
function get_neighbor_graph_x end
function get_neighbor_graph_qK end
function get_neighbor_graph end
function get_sources end
function get_sinks end
function get_sources_sinks end
function get_RO_path end
function group_sum end
function get_RO_paths end
function summary_RO_path end
function SISO_plot end
function get_edge_labels end
function set_proper_bounds_for_graph_plot! end
function get_node_positions end
function get_node_colors end
function get_node_labels end
function get_node_size end
function draw_graph end
function add_vertices_idx! end
function add_arrows! end
function add_nodes_text! end
function set_node_positions end
function draw_qK_neighbor_grh end
function find_bounds end
function add_rgm_colorbar! end
function get_color_map end
